export const LanguageSet = {
    'zn-CN':[
        { id: 'afr', value: '南非荷兰语' },
        { id: 'ara', value: '阿拉伯语' },
        { id: 'aze', value: '阿塞拜疆语' },
        { id: 'bel', value: '白俄罗斯语' },
        { id: 'ben', value: '孟加拉语' },
        { id: 'bul', value: '保加利亚语' },
        { id: 'cat', value: '加泰罗尼亚语' },
        { id: 'ces', value: '捷克语' },
        { id: 'chi_sim', value: '中文' },
        { id: 'chi_tra', value: '繁体中文' },
        { id: 'chr', value: '切罗基语' },
        { id: 'dan', value: '丹麦语' },
        { id: 'deu', value: '德语' },
        { id: 'ell', value: '希腊语' },
        { id: 'eng', value: '英语' },
        { id: 'enm', value: '英语（古代）' },
        { id: 'meme', value: '网络迷因' },
        { id: 'epo', value: '世界语' },
        { id: 'epo_alt', value: '世界语替代' },
        { id: 'equ', value: '数学' },
        { id: 'est', value: '爱沙尼亚语' },
        { id: 'eus', value: '巴斯克语' },
        { id: 'fin', value: '芬兰语' },
        { id: 'fra', value: '法语' },
        { id: 'frk', value: '法兰克语' },
        { id: 'frm', value: '法语（古代）' },
        { id: 'glg', value: '加利西亚语' },
        { id: 'grc', value: '古希腊语' },
        { id: 'heb', value: '希伯来语' },
        { id: 'hin', value: '印地语' },
        { id: 'hrv', value: '克罗地亚语' },
        { id: 'hun', value: '匈牙利语' },
        { id: 'ind', value: '印尼语' },
        { id: 'isl', value: '冰岛语' },
        { id: 'ita', value: '意大利语' },
        { id: 'ita_old', value: '意大利语（古代）' },
        { id: 'jpn', value: '日语' },
        { id: 'kan', value: '卡纳达语' },
        { id: 'kor', value: '韩语' },
        { id: 'lav', value: '拉脱维亚语' },
        { id: 'lit', value: '立陶宛语' },
        { id: 'mal', value: '马拉雅拉姆语' },
        { id: 'mkd', value: '马其顿语' },
        { id: 'mlt', value: '马耳他语' },
        { id: 'msa', value: '马来语' },
        { id: 'nld', value: '荷兰语' },
        { id: 'nor', value: '挪威语' },
        { id: 'pol', value: '波兰语' },
        { id: 'por', value: '葡萄牙语' },
        { id: 'ron', value: '罗马尼亚语' },
        { id: 'rus', value: '俄语' },
        { id: 'slk', value: '斯洛伐克语' },
        { id: 'slv', value: '斯洛文尼亚语' },
        { id: 'spa', value: '西班牙语' },
        { id: 'spa_old', value: '旧西班牙语' },
        { id: 'sqi', value: '阿尔巴尼亚语' },
        { id: 'srp', value: '塞尔维亚语（拉丁文）' },
        { id: 'swa', value: '斯瓦希里语' },
        { id: 'swe', value: '瑞典语' },
        { id: 'tam', value: '泰米尔语' },
        { id: 'tel', value: '泰卢固语' },
        { id: 'tgl', value: '他加禄语' },
        { id: 'tha', value: '泰语' },
        { id: 'tur', value: '土耳其语' },
        { id: 'ukr', value: '乌克兰语' },
        { id: 'vie', value: '越南语' }
    ],
    'zn-TW': [
        { id: 'afr', value: '南非荷蘭語' },
        { id: 'ara', value: '阿拉伯語' },
        { id: 'aze', value: '阿塞拜疆語' },
        { id: 'bel', value: '白俄羅斯語' },
        { id: 'ben', value: '孟加拉語' },
        { id: 'bul', value: '保加利亞語' },
        { id: 'cat', value: '加泰羅尼亞語' },
        { id: 'ces', value: '捷克語' },
        { id: 'chi_sim', value: '中文' },
        { id: 'chi_tra', value: '繁體中文' },
        { id: 'chr', value: '切羅基語' },
        { id: 'dan', value: '丹麥語' },
        { id: 'deu', value: '德語' },
        { id: 'ell', value: '希臘語' },
        { id: 'eng', value: '英語' },
        { id: 'enm', value: '英語（古代）' },
        { id: 'meme', value: '網絡迷因' },
        { id: 'epo', value: '世界語' },
        { id: 'epo_alt', value: '世界語替代' },
        { id: 'equ', value: '數學' },
        { id: 'est', value: '愛沙尼亞語' },
        { id: 'eus', value: '巴斯克語' },
        { id: 'fin', value: '芬蘭語' },
        { id: 'fra', value: '法語' },
        { id: 'frk', value: '法蘭克語' },
        { id: 'frm', value: '法語（古代）' },
        { id: 'glg', value: '加利西亞語' },
        { id: 'grc', value: '古希臘語' },
        { id: 'heb', value: '希伯來語' },
        { id: 'hin', value: '印地語' },
        { id: 'hrv', value: '克羅地亞語' },
        { id: 'hun', value: '匈牙利語' },
        { id: 'ind', value: '印尼語' },
        { id: 'isl', value: '冰島語' },
        { id: 'ita', value: '意大利語' },
        { id: 'ita_old', value: '意大利語（古代）' },
        { id: 'jpn', value: '日語' },
        { id: 'kan', value: '卡納達語' },
        { id: 'kor', value: '韓語' },
        { id: 'lav', value: '拉脫維亞語' },
        { id: 'lit', value: '立陶宛語' },
        { id: 'mal', value: '馬拉雅拉姆語' },
        { id: 'mkd', value: '馬其頓語' },
        { id: 'mlt', value: '馬耳他語' },
        { id: 'msa', value: '馬來語' },
        { id: 'nld', value: '荷蘭語' },
        { id: 'nor', value: '挪威語' },
        { id: 'pol', value: '波蘭語' },
        { id: 'por', value: '葡萄牙語' },
        { id: 'ron', value: '羅馬尼亞語' },
        { id: 'rus', value: '俄語' },
        { id: 'slk', value: '斯洛伐克語' },
        { id: 'slv', value: '斯洛文尼亞語' },
        { id: 'spa', value: '西班牙語' },
        { id: 'spa_old', value: '舊西班牙語' },
        { id: 'sqi', value: '阿爾巴尼亞語' },
        { id: 'srp', value: '塞爾維亞語（拉丁文）' },
        { id: 'swa', value: '斯瓦希里語' },
        { id: 'swe', value: '瑞典語' },
        { id: 'tam', value: '泰米爾語' },
        { id: 'tel', value: '泰盧固語' },
        { id: 'tgl', value: '他加祿語' },
        { id: 'tha', value: '泰語' },
        { id: 'tur', value: '土耳其語' },
        { id: 'ukr', value: '烏克蘭語' },
        { id: 'vie', value: '越南語' }
    ],
    'ja': [
        { id: 'afr', value: 'アフリカーンス語' },
        { id: 'ara', value: 'アラビア語' },
        { id: 'aze', value: 'アゼルバイジャン語' },
        { id: 'bel', value: 'ベラルーシ語' },
        { id: 'ben', value: 'ベンガル語' },
        { id: 'bul', value: 'ブルガリア語' },
        { id: 'cat', value: 'カタロニア語' },
        { id: 'ces', value: 'チェコ語' },
        { id: 'chi_sim', value: '中国語' },
        { id: 'chi_tra', value: '繁体中国語' },
        { id: 'chr', value: 'チェロキー語' },
        { id: 'dan', value: 'デンマーク語' },
        { id: 'deu', value: 'ドイツ語' },
        { id: 'ell', value: 'ギリシャ語' },
        { id: 'eng', value: '英語' },
        { id: 'enm', value: '英語（古代）' },
        { id: 'meme', value: 'インターネットミーム' },
        { id: 'epo', value: 'エスペラント語' },
        { id: 'epo_alt', value: 'エスペラント代替' },
        { id: 'equ', value: '数学' },
        { id: 'est', value: 'エストニア語' },
        { id: 'eus', value: 'バスク語' },
        { id: 'fin', value: 'フィンランド語' },
        { id: 'fra', value: 'フランス語' },
        { id: 'frk', value: 'フランク語' },
        { id: 'frm', value: 'フランス語（古代）' },
        { id: 'glg', value: 'ガリシア語' },
        { id: 'grc', value: '古代ギリシャ語' },
        { id: 'heb', value: 'ヘブライ語' },
        { id: 'hin', value: 'ヒンディー語' },
        { id: 'hrv', value: 'クロアチア語' },
        { id: 'hun', value: 'ハンガリー語' },
        { id: 'ind', value: 'インドネシア語' },
        { id: 'isl', value: 'アイスランド語' },
        { id: 'ita', value: 'イタリア語' },
        { id: 'ita_old', value: 'イタリア語（古代）' },
        { id: 'jpn', value: '日本語' },
        { id: 'kan', value: 'カンナダ語' },
        { id: 'kor', value: '韓国語' },
        { id: 'lav', value: 'ラトビア語' },
        { id: 'lit', value: 'リトアニア語' },
        { id: 'mal', value: 'マラヤーラム語' },
        { id: 'mkd', value: 'マケドニア語' },
        { id: 'mlt', value: 'マルタ語' },
        { id: 'msa', value: 'マレー語' },
        { id: 'nld', value: 'オランダ語' },
        { id: 'nor', value: 'ノルウェー語' },
        { id: 'pol', value: 'ポーランド語' },
        { id: 'por', value: 'ポルトガル語' },
        { id: 'ron', value: 'ルーマニア語' },
        { id: 'rus', value: 'ロシア語' },
        { id: 'slk', value: 'スロバキア語' },
        { id: 'slv', value: 'スロベニア語' },
        { id: 'spa', value: 'スペイン語' },
        { id: 'spa_old', value: '古いスペイン語' },
        { id: 'sqi', value: 'アルバニア語' },
        { id: 'srp', value: 'セルビア語（ラテン語）' },
        { id: 'swa', value: 'スワヒリ語' },
        { id: 'swe', value: 'スウェーデン語' },
        { id: 'tam', value: 'タミル語' },
        { id: 'tel', value: 'テルグ語' },
        { id: 'tgl', value: 'タガログ語' },
        { id: 'tha', value: 'タイ語' },
        { id: 'tur', value: 'トルコ語' },
        { id: 'ukr', value: 'ウクライナ語' },
        { id: 'vie', value: 'ベトナム語' }
    ],
    'ko': [
        { id: 'afr', value: '아프리칸스어' },
        { id: 'ara', value: '아랍어' },
        { id: 'aze', value: '아제르바이잔어' },
        { id: 'bel', value: '벨라루스어' },
        { id: 'ben', value: '벵골어' },
        { id: 'bul', value: '불가리아어' },
        { id: 'cat', value: '카탈로니아어' },
        { id: 'ces', value: '체코어' },
        { id: 'chi_sim', value: '중국어' },
        { id: 'chi_tra', value: '번체 중국어' },
        { id: 'chr', value: '체로키어' },
        { id: 'dan', value: '덴마크어' },
        { id: 'deu', value: '독일어' },
        { id: 'ell', value: '그리스어' },
        { id: 'eng', value: '영어' },
        { id: 'enm', value: '영어 (옛날)' },
        { id: 'meme', value: '인터넷 미믹' },
        { id: 'epo', value: '에스페란토어' },
        { id: 'epo_alt', value: '대체 에스페란토어' },
        { id: 'equ', value: '수학' },
        { id: 'est', value: '에스토니아어' },
        { id: 'eus', value: '바스크어' },
        { id: 'fin', value: '핀란드어' },
        { id: 'fra', value: '프랑스어' },
        { id: 'frk', value: '프랑크어' },
        { id: 'frm', value: '프랑스어 (옛날)' },
        { id: 'glg', value: '갈리시아어' },
        { id: 'grc', value: '고대 그리스어' },
        { id: 'heb', value: '히브리어' },
        { id: 'hin', value: '힌디어' },
        { id: 'hrv', value: '크로아티아어' },
        { id: 'hun', value: '헝가리어' },
        { id: 'ind', value: '인도네시아어' },
        { id: 'isl', value: '아이슬란드어' },
        { id: 'ita', value: '이탈리아어' },
        { id: 'ita_old', value: '이탈리아어 (옛날)' },
        { id: 'jpn', value: '일본어' },
        { id: 'kan', value: '칸나다어' },
        { id: 'kor', value: '한국어' },
        { id: 'lav', value: '라트비아어' },
        { id: 'lit', value: '리투아니아어' },
        { id: 'mal', value: '말라얄람어' },
        { id: 'mkd', value: '마케도니아어' },
        { id: 'mlt', value: '몰타어' },
        { id: 'msa', value: '말레이어' },
        { id: 'nld', value: '네덜란드어' },
        { id: 'nor', value: '노르웨이어' },
        { id: 'pol', value: '폴란드어' },
        { id: 'por', value: '포르투갈어' },
        { id: 'ron', value: '루마니아어' },
        { id: 'rus', value: '러시아어' },
        { id: 'slk', value: '슬로바키아어' },
        { id: 'slv', value: '슬로베니아어' },
        { id: 'spa', value: '스페인어' },
        { id: 'spa_old', value: '옛 스페인어' },
        { id: 'sqi', value: '알바니아어' },
        { id: 'srp', value: '세르비아어 (라틴어)' },
        { id: 'swa', value: '스와힐리어' },
        { id: 'swe', value: '스웨덴어' },
        { id: 'tam', value: '타밀어' },
        { id: 'tel', value: '텔룬구어' },
        { id: 'tgl', value: '타갈로그어' },
        { id: 'tha', value: '태국어' },
        { id: 'tur', value: '터키어' },
        { id: 'ukr', value: '우크라이나어' },
        { id: 'vie', value: '베트남어' }
    ],
    'fr': [
        { id: 'afr', value: 'Afrikaans' },
        { id: 'ara', value: 'Arabe' },
        { id: 'aze', value: 'Azéri' },
        { id: 'bel', value: 'Biélorusse' },
        { id: 'ben', value: 'Bengali' },
        { id: 'bul', value: 'Bulgare' },
        { id: 'cat', value: 'Catalan' },
        { id: 'ces', value: 'Tchèque' },
        { id: 'chi_sim', value: 'Chinois' },
        { id: 'chi_tra', value: 'Chinois traditionnel' },
        { id: 'chr', value: 'Cherokee' },
        { id: 'dan', value: 'Danois' },
        { id: 'deu', value: 'Allemand' },
        { id: 'ell', value: 'Grec' },
        { id: 'eng', value: 'Anglais' },
        { id: 'enm', value: 'Anglais (ancien)' },
        { id: 'meme', value: 'Mème Internet' },
        { id: 'epo', value: 'Espéranto' },
        { id: 'epo_alt', value: 'Espéranto alternatif' },
        { id: 'equ', value: 'Mathématiques' },
        { id: 'est', value: 'Estonien' },
        { id: 'eus', value: 'Basque' },
        { id: 'fin', value: 'Finnois' },
        { id: 'fra', value: 'Français' },
        { id: 'frk', value: 'Francique' },
        { id: 'frm', value: 'Français (ancien)' },
        { id: 'glg', value: 'Galicien' },
        { id: 'grc', value: 'Grec ancien' },
        { id: 'heb', value: 'Hébreu' },
        { id: 'hin', value: 'Hindi' },
        { id: 'hrv', value: 'Croate' },
        { id: 'hun', value: 'Hongrois' },
        { id: 'ind', value: 'Indonésien' },
        { id: 'isl', value: 'Islandais' },
        { id: 'ita', value: 'Italien' },
        { id: 'ita_old', value: 'Italien (ancien)' },
        { id: 'jpn', value: 'Japonais' },
        { id: 'kan', value: 'Kannada' },
        { id: 'kor', value: 'Coréen' },
        { id: 'lav', value: 'Letton' },
        { id: 'lit', value: 'Lituanien' },
        { id: 'mal', value: 'Malayalam' },
        { id: 'mkd', value: 'Macédonien' },
        { id: 'mlt', value: 'Maltais' },
        { id: 'msa', value: 'Malais' },
        { id: 'nld', value: 'Néerlandais' },
        { id: 'nor', value: 'Norvégien' },
        { id: 'pol', value: 'Polonais' },
        { id: 'por', value: 'Portugais' },
        { id: 'ron', value: 'Roumain' },
        { id: 'rus', value: 'Russe' },
        { id: 'slk', value: 'Slovaque' },
        { id: 'slv', value: 'Slovène' },
        { id: 'spa', value: 'Espagnol' },
        { id: 'spa_old', value: 'Espagnol ancien' },
        { id: 'sqi', value: 'Albanais' },
        { id: 'srp', value: 'Serbe (latin)' },
        { id: 'swa', value: 'Swahili' },
        { id: 'swe', value: 'Suédois' },
        { id: 'tam', value: 'Tamoul' },
        { id: 'tel', value: 'Télougou' },
        { id: 'tgl', value: 'Tagalog' },
        { id: 'tha', value: 'Thaï' },
        { id: 'tur', value: 'Turc' },
        { id: 'ukr', value: 'Ukrainien' },
        { id: 'vie', value: 'Vietnamien' }
    ],
    'es': [
        { id: 'afr', value: 'Afrikáans' },
        { id: 'ara', value: 'Árabe' },
        { id: 'aze', value: 'Azerbaiyano' },
        { id: 'bel', value: 'Bielorruso' },
        { id: 'ben', value: 'Bengalí' },
        { id: 'bul', value: 'Búlgaro' },
        { id: 'cat', value: 'Catalán' },
        { id: 'ces', value: 'Checo' },
        { id: 'chi_sim', value: 'Chino' },
        { id: 'chi_tra', value: 'Chino tradicional' },
        { id: 'chr', value: 'Cheroqui' },
        { id: 'dan', value: 'Danés' },
        { id: 'deu', value: 'Alemán' },
        { id: 'ell', value: 'Griego' },
        { id: 'eng', value: 'Inglés' },
        { id: 'enm', value: 'Inglés (antiguo)' },
        { id: 'meme', value: 'Meme de Internet' },
        { id: 'epo', value: 'Esperanto' },
        { id: 'epo_alt', value: 'Esperanto alternativo' },
        { id: 'equ', value: 'Matemáticas' },
        { id: 'est', value: 'Estonio' },
        { id: 'eus', value: 'Vasco' },
        { id: 'fin', value: 'Finlandés' },
        { id: 'fra', value: 'Francés' },
        { id: 'frk', value: 'Franconio' },
        { id: 'frm', value: 'Francés (antiguo)' },
        { id: 'glg', value: 'Gallego' },
        { id: 'grc', value: 'Griego antiguo' },
        { id: 'heb', value: 'Hebreo' },
        { id: 'hin', value: 'Hindi' },
        { id: 'hrv', value: 'Croata' },
        { id: 'hun', value: 'Húngaro' },
        { id: 'ind', value: 'Indonesio' },
        { id: 'isl', value: 'Islandés' },
        { id: 'ita', value: 'Italiano' },
        { id: 'ita_old', value: 'Italiano antiguo' },
        { id: 'jpn', value: 'Japonés' },
        { id: 'kan', value: 'Canarés' },
        { id: 'kor', value: 'Coreano' },
        { id: 'lav', value: 'Letón' },
        { id: 'lit', value: 'Lituano' },
        { id: 'mal', value: 'Malayalam' },
        { id: 'mkd', value: 'Macedonio' },
        { id: 'mlt', value: 'Maltés' },
        { id: 'msa', value: 'Malayo' },
        { id: 'nld', value: 'Neerlandés' },
        { id: 'nor', value: 'Noruego' },
        { id: 'pol', value: 'Polaco' },
        { id: 'por', value: 'Portugués' },
        { id: 'ron', value: 'Rumano' },
        { id: 'rus', value: 'Ruso' },
        { id: 'slk', value: 'Eslovaco' },
        { id: 'slv', value: 'Esloveno' },
        { id: 'spa', value: 'Español' },
        { id: 'spa_old', value: 'Español antiguo' },
        { id: 'sqi', value: 'Albanés' },
        { id: 'srp', value: 'Serbio (latín)' },
        { id: 'swa', value: 'Suajili' },
        { id: 'swe', value: 'Sueco' },
        { id: 'tam', value: 'Tamil' },
        { id: 'tel', value: 'Telugu' },
        { id: 'tgl', value: 'Tagalo' },
        { id: 'tha', value: 'Tailandés' },
        { id: 'tur', value: 'Turco' },
        { id: 'ukr', value: 'Ucraniano' },
        { id: 'vie', value: 'Vietnamita' }
    ],
    'de': [
        { id: 'afr', value: 'Afrikaans' },
        { id: 'ara', value: 'Arabisch' },
        { id: 'aze', value: 'Aserbaidschanisch' },
        { id: 'bel', value: 'Weißrussisch' },
        { id: 'ben', value: 'Bengalisch' },
        { id: 'bul', value: 'Bulgarisch' },
        { id: 'cat', value: 'Katalanisch' },
        { id: 'ces', value: 'Tschechisch' },
        { id: 'chi_sim', value: 'Chinesisch' },
        { id: 'chi_tra', value: 'Traditionelles Chinesisch' },
        { id: 'chr', value: 'Cherokee' },
        { id: 'dan', value: 'Dänisch' },
        { id: 'deu', value: 'Deutsch' },
        { id: 'ell', value: 'Griechisch' },
        { id: 'eng', value: 'Englisch' },
        { id: 'enm', value: 'Englisch (Alt)' },
        { id: 'meme', value: 'Internet-Meme' },
        { id: 'epo', value: 'Esperanto' },
        { id: 'epo_alt', value: 'Alternatives Esperanto' },
        { id: 'equ', value: 'Mathematik' },
        { id: 'est', value: 'Estnisch' },
        { id: 'eus', value: 'Baskisch' },
        { id: 'fin', value: 'Finnisch' },
        { id: 'fra', value: 'Französisch' },
        { id: 'frk', value: 'Frankisch' },
        { id: 'frm', value: 'Französisch (Alt)' },
        { id: 'glg', value: 'Galizisch' },
        { id: 'grc', value: 'Altgriechisch' },
        { id: 'heb', value: 'Hebräisch' },
        { id: 'hin', value: 'Hindi' },
        { id: 'hrv', value: 'Kroatisch' },
        { id: 'hun', value: 'Ungarisch' },
        { id: 'ind', value: 'Indonesisch' },
        { id: 'isl', value: 'Isländisch' },
        { id: 'ita', value: 'Italienisch' },
        { id: 'ita_old', value: 'Italienisch (Alt)' },
        { id: 'jpn', value: 'Japanisch' },
        { id: 'kan', value: 'Kannada' },
        { id: 'kor', value: 'Koreanisch' },
        { id: 'lav', value: 'Lettisch' },
        { id: 'lit', value: 'Litauisch' },
        { id: 'mal', value: 'Malayalam' },
        { id: 'mkd', value: 'Mazedonisch' },
        { id: 'mlt', value: 'Maltesisch' },
        { id: 'msa', value: 'Malaiisch' },
        { id: 'nld', value: 'Niederländisch' },
        { id: 'nor', value: 'Norwegisch' },
        { id: 'pol', value: 'Polnisch' },
        { id: 'por', value: 'Portugiesisch' },
        { id: 'ron', value: 'Rumänisch' },
        { id: 'rus', value: 'Russisch' },
        { id: 'slk', value: 'Slowakisch' },
        { id: 'slv', value: 'Slowenisch' },
        { id: 'spa', value: 'Spanisch' },
        { id: 'spa_old', value: 'Altspanisch' },
        { id: 'sqi', value: 'Albanisch' },
        { id: 'srp', value: 'Serbisch (Latein)' },
        { id: 'swa', value: 'Swahili' },
        { id: 'swe', value: 'Schwedisch' },
        { id: 'tam', value: 'Tamil' },
        { id: 'tel', value: 'Telugu' },
        { id: 'tgl', value: 'Tagalog' },
        { id: 'tha', value: 'Thailändisch' },
        { id: 'tur', value: 'Türkisch' },
        { id: 'ukr', value: 'Ukrainisch' },
        { id: 'vie', value: 'Vietnamesisch' }
    ],
    'it': [
        { id: 'afr', value: 'Afrikaans' },
        { id: 'ara', value: 'Arabo' },
        { id: 'aze', value: 'Azero' },
        { id: 'bel', value: 'Bielorusso' },
        { id: 'ben', value: 'Bengalese' },
        { id: 'bul', value: 'Bulgaro' },
        { id: 'cat', value: 'Catalano' },
        { id: 'ces', value: 'Ceco' },
        { id: 'chi_sim', value: 'Cinese' },
        { id: 'chi_tra', value: 'Cinese tradizionale' },
        { id: 'chr', value: 'Cherokee' },
        { id: 'dan', value: 'Danese' },
        { id: 'deu', value: 'Tedesco' },
        { id: 'ell', value: 'Greco' },
        { id: 'eng', value: 'Inglese' },
        { id: 'enm', value: 'Inglese (antico)' },
        { id: 'meme', value: 'Meme di Internet' },
        { id: 'epo', value: 'Esperanto' },
        { id: 'epo_alt', value: 'Esperanto alternativo' },
        { id: 'equ', value: 'Matematica' },
        { id: 'est', value: 'Estone' },
        { id: 'eus', value: 'Basco' },
        { id: 'fin', value: 'Finlandese' },
        { id: 'fra', value: 'Francese' },
        { id: 'frk', value: 'Francone' },
        { id: 'frm', value: 'Francese (antico)' },
        { id: 'glg', value: 'Galiziano' },
        { id: 'grc', value: 'Greco antico' },
        { id: 'heb', value: 'Ebraico' },
        { id: 'hin', value: 'Hindi' },
        { id: 'hrv', value: 'Croato' },
        { id: 'hun', value: 'Ungherese' },
        { id: 'ind', value: 'Indonesiano' },
        { id: 'isl', value: 'Islandese' },
        { id: 'ita', value: 'Italiano' },
        { id: 'ita_old', value: 'Italiano (antico)' },
        { id: 'jpn', value: 'Giapponese' },
        { id: 'kan', value: 'Kannada' },
        { id: 'kor', value: 'Coreano' },
        { id: 'lav', value: 'Lettone' },
        { id: 'lit', value: 'Lituano' },
        { id: 'mal', value: 'Malayalam' },
        { id: 'mkd', value: 'Macedone' },
        { id: 'mlt', value: 'Maltese' },
        { id: 'msa', value: 'Malese' },
        { id: 'nld', value: 'Olandese' },
        { id: 'nor', value: 'Norvegese' },
        { id: 'pol', value: 'Polacco' },
        { id: 'por', value: 'Portoghese' },
        { id: 'ron', value: 'Rumeno' },
        { id: 'rus', value: 'Russo' },
        { id: 'slk', value: 'Slovacco' },
        { id: 'slv', value: 'Sloveno' },
        { id: 'spa', value: 'Spagnolo' },
        { id: 'spa_old', value: 'Spagnolo antico' },
        { id: 'sqi', value: 'Albanese' },
        { id: 'srp', value: 'Serbo (latino)' },
        { id: 'swa', value: 'Swahili' },
        { id: 'swe', value: 'Svedese' },
        { id: 'tam', value: 'Tamil' },
        { id: 'tel', value: 'Telugu' },
        { id: 'tgl', value: 'Tagalog' },
        { id: 'tha', value: 'Tailandese' },
        { id: 'tur', value: 'Turco' },
        { id: 'ukr', value: 'Ucraino' },
        { id: 'vie', value: 'Vietnamita' }
    ],
    'pt': [
        { id: 'afr', value: 'Africâner' },
        { id: 'ara', value: 'Árabe' },
        { id: 'aze', value: 'Azerbaijano' },
        { id: 'bel', value: 'Bielorrusso' },
        { id: 'ben', value: 'Bengali' },
        { id: 'bul', value: 'Búlgaro' },
        { id: 'cat', value: 'Catalão' },
        { id: 'ces', value: 'Tcheco' },
        { id: 'chi_sim', value: 'Chinês' },
        { id: 'chi_tra', value: 'Chinês tradicional' },
        { id: 'chr', value: 'Cherokee' },
        { id: 'dan', value: 'Dinamarquês' },
        { id: 'deu', value: 'Alemão' },
        { id: 'ell', value: 'Grego' },
        { id: 'eng', value: 'Inglês' },
        { id: 'enm', value: 'Inglês antigo' },
        { id: 'meme', value: 'Meme da Internet' },
        { id: 'epo', value: 'Esperanto' },
        { id: 'epo_alt', value: 'Esperanto alternativo' },
        { id: 'equ', value: 'Matemática' },
        { id: 'est', value: 'Estoniano' },
        { id: 'eus', value: 'Basco' },
        { id: 'fin', value: 'Finlandês' },
        { id: 'fra', value: 'Francês' },
        { id: 'frk', value: 'Franco' },
        { id: 'frm', value: 'Francês antigo' },
        { id: 'glg', value: 'Galego' },
        { id: 'grc', value: 'Grego antigo' },
        { id: 'heb', value: 'Hebraico' },
        { id: 'hin', value: 'Hindi' },
        { id: 'hrv', value: 'Croata' },
        { id: 'hun', value: 'Húngaro' },
        { id: 'ind', value: 'Indonésio' },
        { id: 'isl', value: 'Islandês' },
        { id: 'ita', value: 'Italiano' },
        { id: 'ita_old', value: 'Italiano antigo' },
        { id: 'jpn', value: 'Japonês' },
        { id: 'kan', value: 'Canarim' },
        { id: 'kor', value: 'Coreano' },
        { id: 'lav', value: 'Letão' },
        { id: 'lit', value: 'Lituano' },
        { id: 'mal', value: 'Malaiala' },
        { id: 'mkd', value: 'Macedônio' },
        { id: 'mlt', value: 'Maltês' },
        { id: 'msa', value: 'Malaio' },
        { id: 'nld', value: 'Holandês' },
        { id: 'nor', value: 'Norueguês' },
        { id: 'pol', value: 'Polonês' },
        { id: 'por', value: 'Português' },
        { id: 'ron', value: 'Romeno' },
        { id: 'rus', value: 'Russo' },
        { id: 'slk', value: 'Eslovaco' },
        { id: 'slv', value: 'Esloveno' },
        { id: 'spa', value: 'Espanhol' },
        { id: 'spa_old', value: 'Espanhol antigo' },
        { id: 'sqi', value: 'Albanês' },
        { id: 'srp', value: 'Sérvio (latim)' },
        { id: 'swa', value: 'Suaíli' },
        { id: 'swe', value: 'Sueco' },
        { id: 'tam', value: 'Tâmil' },
        { id: 'tel', value: 'Telugu' },
        { id: 'tgl', value: 'Tagalo' },
        { id: 'tha', value: 'Tailandês' },
        { id: 'tur', value: 'Turco' },
        { id: 'ukr', value: 'Ucraniano' },
        { id: 'vie', value: 'Vietnamita' }
    ],
    'ru': [
        { id: 'afr', value: 'Африкаанс' },
        { id: 'ara', value: 'Арабский' },
        { id: 'aze', value: 'Азербайджанский' },
        { id: 'bel', value: 'Белорусский' },
        { id: 'ben', value: 'Бенгальский' },
        { id: 'bul', value: 'Болгарский' },
        { id: 'cat', value: 'Каталанский' },
        { id: 'ces', value: 'Чешский' },
        { id: 'chi_sim', value: 'Китайский' },
        { id: 'chi_tra', value: 'Традиционный китайский' },
        { id: 'chr', value: 'Чероки' },
        { id: 'dan', value: 'Датский' },
        { id: 'deu', value: 'Немецкий' },
        { id: 'ell', value: 'Греческий' },
        { id: 'eng', value: 'Английский' },
        { id: 'enm', value: 'Английский (старый)' },
        { id: 'meme', value: 'Интернет-мем' },
        { id: 'epo', value: 'Эсперанто' },
        { id: 'epo_alt', value: 'Альтернативное эсперанто' },
        { id: 'equ', value: 'Математика' },
        { id: 'est', value: 'Эстонский' },
        { id: 'eus', value: 'Баскский' },
        { id: 'fin', value: 'Финский' },
        { id: 'fra', value: 'Французский' },
        { id: 'frk', value: 'Франкский' },
        { id: 'frm', value: 'Французский (старый)' },
        { id: 'glg', value: 'Галисийский' },
        { id: 'grc', value: 'Древнегреческий' },
        { id: 'heb', value: 'Иврит' },
        { id: 'hin', value: 'Хинди' },
        { id: 'hrv', value: 'Хорватский' },
        { id: 'hun', value: 'Венгерский' },
        { id: 'ind', value: 'Индонезийский' },
        { id: 'isl', value: 'Исландский' },
        { id: 'ita', value: 'Итальянский' },
        { id: 'ita_old', value: 'Итальянский (старый)' },
        { id: 'jpn', value: 'Японский' },
        { id: 'kan', value: 'Каннада' },
        { id: 'kor', value: 'Корейский' },
        { id: 'lav', value: 'Латышский' },
        { id: 'lit', value: 'Литовский' },
        { id: 'mal', value: 'Малаялам' },
        { id: 'mkd', value: 'Македонский' },
        { id: 'mlt', value: 'Мальтийский' },
        { id: 'msa', value: 'Малайский' },
        { id: 'nld', value: 'Голландский' },
        { id: 'nor', value: 'Норвежский' },
        { id: 'pol', value: 'Польский' },
        { id: 'por', value: 'Португальский' },
        { id: 'ron', value: 'Румынский' },
        { id: 'rus', value: 'Русский' },
        { id: 'slk', value: 'Словацкий' },
        { id: 'slv', value: 'Словенский' },
        { id: 'spa', value: 'Испанский' },
        { id: 'spa_old', value: 'Старый испанский' },
        { id: 'sqi', value: 'Албанский' },
        { id: 'srp', value: 'Сербский (латиница)' },
        { id: 'swa', value: 'Суахили' },
        { id: 'swe', value: 'Шведский' },
        { id: 'tam', value: 'Тамильский' },
        { id: 'tel', value: 'Телугу' },
        { id: 'tgl', value: 'Тагальский' },
        { id: 'tha', value: 'Тайский' },
        { id: 'tur', value: 'Турецкий' },
        { id: 'ukr', value: 'Украинский' },
        { id: 'vie', value: 'Вьетнамский' }
    ],
    'ar': [
        { id: 'afr', value: 'الأفريقية' },
        { id: 'ara', value: 'العربية' },
        { id: 'aze', value: 'الأذربيجانية' },
        { id: 'bel', value: 'البيلاروسية' },
        { id: 'ben', value: 'البنغالية' },
        { id: 'bul', value: 'البلغارية' },
        { id: 'cat', value: 'الكتالونية' },
        { id: 'ces', value: 'التشيكية' },
        { id: 'chi_sim', value: 'الصينية' },
        { id: 'chi_tra', value: 'الصينية التقليدية' },
        { id: 'chr', value: 'الشيروكي' },
        { id: 'dan', value: 'الدانماركية' },
        { id: 'deu', value: 'الألمانية' },
        { id: 'ell', value: 'اليونانية' },
        { id: 'eng', value: 'الإنجليزية' },
        { id: 'enm', value: 'الإنجليزية (القديمة)' },
        { id: 'meme', value: 'ميم الإنترنت' },
        { id: 'epo', value: 'الإسبرانتو' },
        { id: 'epo_alt', value: 'الإسبرانتو البديل' },
        { id: 'equ', value: 'الرياضيات' },
        { id: 'est', value: 'الإستونية' },
        { id: 'eus', value: 'الباسكية' },
        { id: 'fin', value: 'الفنلندية' },
        { id: 'fra', value: 'الفرنسية' },
        { id: 'frk', value: 'الفرانكية' },
        { id: 'frm', value: 'الفرنسية (القديمة)' },
        { id: 'glg', value: 'الجاليكية' },
        { id: 'grc', value: 'اليونانية القديمة' },
        { id: 'heb', value: 'العبرية' },
        { id: 'hin', value: 'الهندية' },
        { id: 'hrv', value: 'الكرواتية' },
        { id: 'hun', value: 'المجرية' },
        { id: 'ind', value: 'الإندونيسية' },
        { id: 'isl', value: 'الأيسلندية' },
        { id: 'ita', value: 'الإيطالية' },
        { id: 'ita_old', value: 'الإيطالية (القديمة)' },
        { id: 'jpn', value: 'اليابانية' },
        { id: 'kan', value: 'الكانادا' },
        { id: 'kor', value: 'الكورية' },
        { id: 'lav', value: 'اللاتفية' },
        { id: 'lit', value: 'الليتوانية' },
        { id: 'mal', value: 'المالايالامية' },
        { id: 'mkd', value: 'المقدونية' },
        { id: 'mlt', value: 'المالطية' },
        { id: 'msa', value: 'الماليزية' },
        { id: 'nld', value: 'الهولندية' },
        { id: 'nor', value: 'النرويجية' },
        { id: 'pol', value: 'البولندية' },
        { id: 'por', value: 'البرتغالية' },
        { id: 'ron', value: 'الرومانية' },
        { id: 'rus', value: 'الروسية' },
        { id: 'slk', value: 'السلوفاكية' },
        { id: 'slv', value: 'السلوفينية' },
        { id: 'spa', value: 'الإسبانية' },
        { id: 'spa_old', value: 'الإسبانية القديمة' },
        { id: 'sqi', value: 'الألبانية' },
        { id: 'srp', value: 'الصربية (اللاتينية)' },
        { id: 'swa', value: 'السواحيلية' },
        { id: 'swe', value: 'السويدية' },
        { id: 'tam', value: 'التاميلية' },
        { id: 'tel', value: 'التيلجو' },
        { id: 'tgl', value: 'التاغالوغية' },
        { id: 'tha', value: 'التايلاندية' },
        { id: 'tur', value: 'التركية' },
        { id: 'ukr', value: 'الأوكرانية' },
        { id: 'vie', value: 'الفيتنامية' }
    ],
    'hi': [
        { id: 'afr', value: 'अफ़्रीकांस' },
        { id: 'ara', value: 'अरबी' },
        { id: 'aze', value: 'अज़रबैजानी' },
        { id: 'bel', value: 'बेलारूसियन' },
        { id: 'ben', value: 'बंगाली' },
        { id: 'bul', value: 'बल्गेरियाई' },
        { id: 'cat', value: 'कैटलन' },
        { id: 'ces', value: 'चेक' },
        { id: 'chi_sim', value: 'चीनी' },
        { id: 'chi_tra', value: 'पारंपरिक चीनी' },
        { id: 'chr', value: 'चेरोकी' },
        { id: 'dan', value: 'डेनिश' },
        { id: 'deu', value: 'जर्मन' },
        { id: 'ell', value: 'यूनानी' },
        { id: 'eng', value: 'अंग्रेज़ी' },
        { id: 'enm', value: 'पुरानी अंग्रेज़ी' },
        { id: 'meme', value: 'इंटरनेट मीम' },
        { id: 'epo', value: 'एस्पेरांतो' },
        { id: 'epo_alt', value: 'वैकल्पिक एस्पेरांतो' },
        { id: 'equ', value: 'गणित' },
        { id: 'est', value: 'एस्टोनियन' },
        { id: 'eus', value: 'बास्क' },
        { id: 'fin', value: 'फ़िनिश' },
        { id: 'fra', value: 'फ़्रेंच' },
        { id: 'frk', value: 'फ्रैंक' },
        { id: 'frm', value: 'पुरानी फ़्रेंच' },
        { id: 'glg', value: 'गैलिशियन' },
        { id: 'grc', value: 'प्राचीन यूनानी' },
        { id: 'heb', value: 'हिब्रू' },
        { id: 'hin', value: 'हिन्दी' },
        { id: 'hrv', value: 'क्रोएशियाई' },
        { id: 'hun', value: 'हंगेरियन' },
        { id: 'ind', value: 'इंडोनेशियाई' },
        { id: 'isl', value: 'आइसलैंडिक' },
        { id: 'ita', value: 'इतालवी' },
        { id: 'ita_old', value: 'पुरानी इतालवी' },
        { id: 'jpn', value: 'जापानी' },
        { id: 'kan', value: 'कन्नड़' },
        { id: 'kor', value: 'कोरियाई' },
        { id: 'lav', value: 'लातवियाई' },
        { id: 'lit', value: 'लिथुआनियाई' },
        { id: 'mal', value: 'मलयालम' },
        { id: 'mkd', value: 'मैसेडोनियन' },
        { id: 'mlt', value: 'माल्टीज़' },
        { id: 'msa', value: 'मलय' },
        { id: 'nld', value: 'डच' },
        { id: 'nor', value: 'नॉर्वेजियन' },
        { id: 'pol', value: 'पोलिश' },
        { id: 'por', value: 'पुर्तगाली' },
        { id: 'ron', value: 'रोमानियाई' },
        { id: 'rus', value: 'रूसी' },
        { id: 'slk', value: 'स्लोवाक' },
        { id: 'slv', value: 'स्लोवेनियाई' },
        { id: 'spa', value: 'स्पेनिश' },
        { id: 'spa_old', value: 'पुरानी स्पेनिश' },
        { id: 'sqi', value: 'अल्बेनियन' },
        { id: 'srp', value: 'सर्बियन (लैटिन)' },
        { id: 'swa', value: 'स्वाहिली' },
        { id: 'swe', value: 'स्वीडिश' },
        { id: 'tam', value: 'तमिल' },
        { id: 'tel', value: 'तेलुगू' },
        { id: 'tgl', value: 'तागालोग' },
        { id: 'tha', value: 'थाई' },
        { id: 'tur', value: 'तुर्की' },
        { id: 'ukr', value: 'यूक्रेनियन' },
        { id: 'vie', value: 'वियतनामी' }
    ],
    'th': [
        { id: 'afr', value: 'แอฟริกานส์' },
        { id: 'ara', value: 'อาหรับ' },
        { id: 'aze', value: 'อาเซอร์ไบจาน' },
        { id: 'bel', value: 'เบลารุส' },
        { id: 'ben', value: 'เบงกาลี' },
        { id: 'bul', value: 'บัลแกเรีย' },
        { id: 'cat', value: 'คาตาลัน' },
        { id: 'ces', value: 'เช็ก' },
        { id: 'chi_sim', value: 'จีน' },
        { id: 'chi_tra', value: 'จีนดั้งเดิม' },
        { id: 'chr', value: 'เชโรกี' },
        { id: 'dan', value: 'เดนมาร์ก' },
        { id: 'deu', value: 'เยอรมัน' },
        { id: 'ell', value: 'กรีก' },
        { id: 'eng', value: 'อังกฤษ' },
        { id: 'enm', value: 'อังกฤษโบราณ' },
        { id: 'meme', value: 'มีมอินเทอร์เน็ต' },
        { id: 'epo', value: 'เอสเปอรันโต' },
        { id: 'epo_alt', value: 'เอสเปอรันโตทางเลือก' },
        { id: 'equ', value: 'คณิตศาสตร์' },
        { id: 'est', value: 'เอสโตเนีย' },
        { id: 'eus', value: 'บาสก์' },
        { id: 'fin', value: 'ฟินแลนด์' },
        { id: 'fra', value: 'ฝรั่งเศส' },
        { id: 'frk', value: 'ฝรั่งเศส' },
        { id: 'frm', value: 'ฝรั่งเศสโบราณ' },
        { id: 'glg', value: 'กาลิเซีย' },
        { id: 'grc', value: 'กรีกโบราณ' },
        { id: 'heb', value: 'ฮีบรู' },
        { id: 'hin', value: 'ฮินดี' },
        { id: 'hrv', value: 'โครเอเชีย' },
        { id: 'hun', value: 'ฮังการี' },
        { id: 'ind', value: 'อินโดนีเซีย' },
        { id: 'isl', value: 'ไอซ์แลนด์' },
        { id: 'ita', value: 'อิตาลี' },
        { id: 'ita_old', value: 'อิตาลีโบราณ' },
        { id: 'jpn', value: 'ญี่ปุ่น' },
        { id: 'kan', value: 'กันนาดา' },
        { id: 'kor', value: 'เกาหลี' },
        { id: 'lav', value: 'ลัตเวีย' },
        { id: 'lit', value: 'ลิทัวเนีย' },
        { id: 'mal', value: 'มาลายาลัม' },
        { id: 'mkd', value: 'มาซิโดเนีย' },
        { id: 'mlt', value: 'มอลตา' },
        { id: 'msa', value: 'มาเลย์' },
        { id: 'nld', value: 'ดัตช์' },
        { id: 'nor', value: 'นอร์เวย์' },
        { id: 'pol', value: 'โปแลนด์' },
        { id: 'por', value: 'โปรตุเกส' },
        { id: 'ron', value: 'โรมาเนีย' },
        { id: 'rus', value: 'รัสเซีย' },
        { id: 'slk', value: 'สโลวัก' },
        { id: 'slv', value: 'สโลวีเนีย' },
        { id: 'spa', value: 'สเปน' },
        { id: 'spa_old', value: 'สเปนโบราณ' },
        { id: 'sqi', value: 'แอลเบเนีย' },
        { id: 'srp', value: 'เซอร์เบีย (ละติน)' },
        { id: 'swa', value: 'สวาฮิลี' },
        { id: 'swe', value: 'สวีเดน' },
        { id: 'tam', value: 'ทมิล' },
        { id: 'tel', value: 'เตลูกู' },
        { id: 'tgl', value: 'ตากาล็อก' },
        { id: 'tha', value: 'ไทย' },
        { id: 'tur', value: 'ตุรกี' },
        { id: 'ukr', value: 'ยูเครน' },
        { id: 'vie', value: 'เวียดนาม' }
    ],
    'en': [
        { id: 'afr', value: 'Afrikaans'},
        { id: 'ara', value: 'Arabic'},
        { id: 'aze', value: 'Azerbaijani'},
        { id: 'bel', value: 'Belarusian'},
        { id: 'ben', value: 'Bengali'},
        { id: 'bul', value: 'Bulgarian'},
        { id: 'cat', value: 'Catalan'},
        { id: 'ces', value: 'Czech'},
        { id: 'chi_sim', value: 'Chinese'},
        { id: 'chi_tra', value: 'Traditional Chinese'},
        { id: 'chr', value: 'Cherokee'},
        { id: 'dan', value: 'Danish'},
        { id: 'deu', value: 'German'},
        { id: 'ell', value: 'Greek'},
        { id: 'eng', value: 'English'},
        { id: 'enm', value: 'English (Old)'},
        { id: 'meme', value: 'Internet Meme'},
        { id: 'epo', value: 'Esperanto'},
        { id: 'epo_alt', value: 'Esperanto alternative '},
        { id: 'equ', value: 'Math'},
        { id: 'est', value: 'Estonian'},
        { id: 'eus', value: 'Basque'},
        { id: 'fin', value: 'Finnish'},
        { id: 'fra', value: 'French'},
        { id: 'frk', value: 'Frankish'},
        { id: 'frm', value: 'French (Old)'},
        { id: 'glg', value: 'Galician '},
        { id: 'grc', value: 'Ancient Greek'},
        { id: 'heb', value: 'Hebrew'},
        { id: 'hin', value: 'Hindi'},
        { id: 'hrv', value: 'Croatian'},
        { id: 'hun', value: 'Hungarian'},
        { id: 'ind', value: 'Indonesian'},
        { id: 'isl', value: 'Icelandic'},
        { id: 'ita', value: 'Italian'},
        { id: 'ita_old', value: 'Italian (Old)'},
        { id: 'jpn', value: 'Japanese'},
        { id: 'kan', value: 'Kannada'},
        { id: 'kor', value: 'Korean'},
        { id: 'lav', value: 'Latvian'},
        { id: 'lit', value: 'Lithuanian'},
        { id: 'mal', value: 'Malayalam'},
        { id: 'mkd', value: 'Macedonian'},
        { id: 'mlt', value: 'Maltese'},
        { id: 'msa', value: 'Malay'},
        { id: 'nld', value: 'Dutch'},
        { id: 'nor', value: 'Norwegian'},
        { id: 'pol', value: 'Polish'},
        { id: 'por', value: 'Portuguese'},
        { id: 'ron', value: 'Romanian'},
        { id: 'rus', value: 'Russian'},
        { id: 'slk', value: 'Slovakian'},
        { id: 'slv', value: 'Slovenian'},
        { id: 'spa', value: 'Spanish'},
        { id: 'spa_old', value: 'Old Spanish'},
        { id: 'sqi', value: 'Albanian'},
        { id: 'srp', value: 'Serbian (Latin)'},
        { id: 'swa', value: 'Swahili'},
        { id: 'swe', value: 'Swedish'},
        { id: 'tam', value: 'Tamil'},
        { id: 'tel', value: 'Telugu'},
        { id: 'tgl', value: 'Tagalog'},
        { id: 'tha', value: 'Thai'},
        { id: 'tur', value: 'Turkish'},
        { id: 'ukr', value: 'Ukrainian'},
        { id: 'vie', value: 'Vietnamese'}
    ]
}

export const getLanguageSet = (lang: string): {id: string, value: string}[] => {
    // get lang in Language object
    const keys = Object.keys(LanguageSet) as Array<keyof typeof LanguageSet>;
    // need to check contains
    const index = keys.findIndex((l: string) => lang.toLowerCase().includes(l.toLowerCase()));
    if (index === -1) {
        return LanguageSet['en'];
    }
    return LanguageSet[keys[index]];
}